### ISSUE TITLE
How do I form the export URL?

### ISSUE THREAD

**Issue by andyra** [statamic/exporter#5]
The instructions say to visit `http://v1-site.com/TRIGGER/exporter/export`. It's clear that some of the URL contains placeholders that need to be filled in with specific info, but it's not clear what those are. 

- What should `v1-site.com` be replaced with? I'm assuming the URL I'm running Statamic from. If that's true, something like `example.com` or `mywebsite.com` might be a more understandable placeholder
- What should `TRIGGER` be replaced with?

**Comment by jasonvarga** [comment]
If your Statamic version 1 site is `my-statamic-site.com` then you should go to `http://my-statamic-site.com/TRIGGER/exporter/export`. No other substitutions necessary.

**Comment by andyra** [comment]
Oooooh, v1 like Statamic v1. I get it! I guess that implies this won't work for exporting data from Statamic 2?

**Comment by jasonvarga** [comment]
Right, this project exports data _from_ Statamic 1, so you can then _import_ it into Statamic 2.

**Comment by andyra** [comment]
Thanks @jasonvarga, that makes sense.

**Comment by jasonvarga** [comment]
I updated the readme to make it a bit clearer, sorry for the confusion!
